{
 "title": "Langstream / Apps",
 "description": "Apps related metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "jvm_memory_bytes_used{namespace=~\".+\"}"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "jvm_memory_bytes_used{namespace=~\"ls-($tenant|All)\",langstream_application=~\".+\"}"
    }
   },
   {
    "name": "agent",
    "label": "Agent",
    "query": {
     "query": "jvm_memory_bytes_used{namespace=~\"ls-($tenant|All)\",langstream_application=~\"($application|All)\",langstream_agent=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "OpenAI Comsumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "agent" },
  {
   "title": "OpenAI Embeddings requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "openai_embeddings_num_calls_total",
     "legendFormat": "Http requests"
    }
   ]
  },
  {
   "title": "OpenAI Embeddings Texts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(openai_embeddings_num_texts_total)",
     "legendFormat": "Texts"
    }
   ]
  },
  {
   "title": "OpenAI Embeddings Texts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(openai_embeddings_prompt_tokens_total)",
     "legendFormat": "Prompt tokens"
    },
    {
     "expr": "sum(openai_embeddings_total_tokens_total)",
     "legendFormat": "Total tokens"
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Executors ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"ls-.*\", condition=\"true\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"ls-.*\", condition=\"false\"})",
     "legendFormat": "Failing"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"ls-.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"ls-$tenant\", pod=~\"$application-$agent-.*\", resource=\"cpu\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"ls-$tenant\", pod=~\"$application-$agent-.*\", resource=\"memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Tenant: $tenant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "tenant" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=~\"ls-$tenant\", pod=~\"$application-$agent-.*\"}[60s]) * 100\n\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_bytes_used{namespace=~\"ls-$tenant\",pod=~\"$application-$agent-.*\"})",
     "legendFormat": "Used - {{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_bytes_max{namespace=~\"ls-$tenant\",pod=~\"$application-$agent-.*\"})",
     "legendFormat": "Max: {{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_bytes_committed{namespace=~\"ls-$tenant\",pod=~\"$application-$agent-.*\"})",
     "legendFormat": "Committed: {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"ls-$tenant\", pod=~\"$application-$agent-.*\", resource=\"memory\"}",
     "legendFormat": "Kube limit: {{pod}}"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"ls-$tenant\",pod=~\"$application-$agent-.*\"}[60s])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running executors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"ls-$tenant\", condition=\"true\", pod=~\"$application-$agent-.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failing executors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"ls-$tenant\", condition=\"false\", pod=~\"$application-$agent-.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed deployments",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "\nsum(label_replace(\n    kube_pod_status_phase{namespace=~\"ls-$tenant\", phase=~\"Failed|Unknown\", pod=~\"langstream-runtime-deployer-.*\"},\n    \"application1\",\"$1\",\"pod\", \"(.*)-(.*)\"\n    )\n)by(application1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}