controlPlane:
  replicaCount: 1
  image:
    repository: public.ecr.aws/y3i6u2n7/datastax-public/langstream-control-plane
    pullPolicy: IfNotPresent
    tag: "0.0.3"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "langstream-control-plane"
    roleBinding:
      name: "langstream-control-plane-role-binding"

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8090
  resources:
    requests:
       cpu: 200m
       memory: 256Mi
  liveness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config:
      application.storage.global.type: kubernetes

client:
  replicaCount: 1
  image:
    repository: public.ecr.aws/y3i6u2n7/datastax-public/langstream-client
    pullPolicy: IfNotPresent
    tag: "0.0.3"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config: {}

deployer:
  replicaCount: 1
  image:
    repository: public.ecr.aws/y3i6u2n7/datastax-public/langstream-deployer
    pullPolicy: IfNotPresent
    tag: "0.0.3"
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "langstream-deployer"
    roleBinding:
      name: "langstream-deployer-role-binding"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config:
      agentResources: {}
      clusterRuntime:
        kubernetes: {}
      codeStorage:
        type: none
        endpoint: ""
      podTemplate:
        tolerations: []
        nodeSelector: {}



apiGateway:
  replicaCount: 1
  image:
    repository: public.ecr.aws/y3i6u2n7/datastax-public/langstream-api-gateway
    pullPolicy: IfNotPresent
    tag: "0.0.3"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "langstream-api-gateway"
    roleBinding:
      name: "langstream-api-gateway-role-binding"

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8091
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config: {}

runtime:
  repository: public.ecr.aws/y3i6u2n7/datastax-public/langstream-runtime:0.0.3
  imagePullPolicy: IfNotPresent

tenants:
  defaultTenant:
    create: true
    name: default
  storageType: kubernetes
  namespacePrefix: langstream-


codeStorage:
  type: none
  configuration: {}
