
# Global settings applied to all the images
images:
  tag: ""


controlPlane:
  replicaCount: 1
  image:
    repository:  ghcr.io/langstream/langstream-control-plane
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "langstream-control-plane"
    roleBinding:
      name: "langstream-control-plane-role-binding"

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8090
  resources:
    requests:
       cpu: 0.25
       memory: 256Mi
  liveness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config:
      application.storage.global.type: kubernetes

client:
  replicaCount: 1
  image:
    repository: ghcr.io/langstream/langstream-cli
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: 
    requests:
      cpu: 0.25
      memory: 256Mi
  app:
    config: {}

deployer:
  replicaCount: 1
  image:
    repository: ghcr.io/langstream/langstream-deployer
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "langstream-deployer"
    roleBinding:
      name: "langstream-deployer-role-binding"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 0.25
      memory: 256Mi
  liveness:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config:
      agentResources: {}
      clusterRuntime:
        kubernetes: {}
      codeStorage:
        type: none
        endpoint: ""
      podTemplate:
        tolerations: []
        nodeSelector: {}
        annotations: {}
      agentPodTemplate:
        tolerations: []
        nodeSelector: {}
        annotations: {}
      appDeployerPodTemplate:
        tolerations: []
        nodeSelector: {}
        annotations: {}



apiGateway:
  replicaCount: 1
  image:
    repository: ghcr.io/langstream/langstream-api-gateway
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "langstream-api-gateway"
    roleBinding:
      name: "langstream-api-gateway-role-binding"

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8091
  resources:
    requests:
      cpu: 0.25
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  liveness:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
  app:
    config: {}

runtime:
  image: ghcr.io/langstream/langstream-runtime
  imagePullPolicy: IfNotPresent
  imageTag: ""

tenants:
  defaultTenant:
    create: true
    name: default
  storageType: kubernetes
  namespacePrefix: langstream-


codeStorage:
  type: none
  configuration: {}
