global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'langstream'
    static_configs:
      - targets: ['host.docker.internal:8790']
        labels:
          namespace: 'ls-docker'
          pod: 'app-docker-local'
          langstream_application: 'app'
          langstream_agent: 'docker'
