apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langstream.deployerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "langstream.deployerLabels" . | nindent 4 }}
data:
  DEPLOYER_CLUSTER_RUNTIME: |
    kubernetes:
     namespace-prefix: {{ .Values.tenants.namespacePrefix }}
     image: "{{ include "langstream.runtimeImage" . }}"
     image-pull-policy: {{ .Values.runtime.imagePullPolicy }}
{{- if .Values.deployer.app.config.clusterRuntime.kubernetes }}
{{- range $key, $val := $.Values.deployer.app.config.clusterRuntime.kubernetes }}
     {{ $key }}: {{ $val | toString | replace "\"" "" | trim | quote }}
{{- end }}
{{- end }}
  DEPLOYER_CODE_STORAGE: |
    type: {{ .Values.codeStorage.type }}
{{- range $key, $val := $.Values.codeStorage.configuration }}
    {{ $key }}: {{ $val | toString | replace "\"" "" | trim | quote }}
{{- end }}
  DEPLOYER_RUNTIME_IMAGE: "{{ include "langstream.runtimeImage" . }}"
  DEPLOYER_RUNTIME_IMAGE_PULL_POLICY: {{ .Values.runtime.imagePullPolicy }}
  DEPLOYER_GLOBAL_STORAGE: |
    type: {{ .Values.globalStorage.type }}
{{- range $key, $val := $.Values.globalStorage.configuration }}
    {{ $key }}: {{ $val | toString | replace "\"" "" | trim | quote }}
{{- end }}

{{- range $key, $val := $.Values.deployer.app.config }}
{{- if eq "codeStorage" $key }}
{{- else if eq "clusterRuntime" $key }}
{{- else }}
  {{- if kindIs "map" $val }}
  DEPLOYER_{{ $key | replace "-" "" | replace "\"" "." | snakecase | upper | replace "." "_"  }}: |
{{ $val | toYaml | indent 4 }}
  {{- else }}
  DEPLOYER_{{ $key | replace "-" "" | replace "\"" "." | snakecase | upper | replace "." "_"  }}: "{{- $val -}}"
  {{- end }}
{{- end }}
{{- end }}


