apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langstream.controlPlaneFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "langstream.controlPlaneLabels" . | nindent 4 }}
data:
  APPLICATION_STORAGE_GLOBAL_TYPE: {{ .Values.globalStorage.type }}
{{- range $key, $val := $.Values.globalStorage.configuration }}
  APPLICATION_STORAGE_GLOBAL_CONFIGURATION_{{ $key | replace "-" "" | replace "\"" "." | snakecase | upper | replace "." "_" }}: {{ $val | toString | replace "\"" "" | trim | quote }}
{{- end }}
  APPLICATION_STORAGE_APPS_CONFIGURATION_CONTROLPLANEURL: "http://{{ include "langstream.controlPlaneFullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.controlPlane.service.port }}"
  APPLICATION_STORAGE_APPS_CONFIGURATION_DEPLOYERRUNTIME_IMAGE: "{{ include "langstream.runtimeImage" . }}"
  APPLICATION_STORAGE_APPS_CONFIGURATION_DEPLOYERRUNTIME_IMAGE_PULL_POLICY: {{ .Values.runtime.imagePullPolicy }}
  APPLICATION_STORAGE_APPS_CONFIGURATION_NAMESPACEPREFIX: {{ .Values.tenants.namespacePrefix }}
  APPLICATION_STORAGE_APPS_TYPE: {{ .Values.tenants.storageType }}
  APPLICATION_STORAGE_CODE_TYPE: {{ .Values.codeStorage.type }}
{{- range $key, $val := $.Values.codeStorage.configuration }}
  APPLICATION_STORAGE_CODE_CONFIGURATION_{{ $key | replace "-" "" | replace "\"" "." | snakecase | upper | replace "." "_" }}: {{ $val | toString | replace "\"" "" | trim | quote }}
{{- end }}
  APPLICATION_TENANTS_DEFAULTTENANT_CREATE: "{{ .Values.tenants.defaultTenant.create }}"
  APPLICATION_TENANTS_DEFAULTTENANT_NAME: "{{ .Values.tenants.defaultTenant.name }}"
{{- range $key, $val := $.Values.controlPlane.app.config }}
  {{ $key | replace "-" "" | replace "\"" "." | snakecase | upper | replace "." "_"  }}: {{ $val | toString | replace "\"" "" | trim | quote }}
{{- end }}
