name: Update README
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  readme:
    name: Readme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Readme
        run: |
          ./generate-readme.sh
          cp README.md /tmp/README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Generate Readme gh-pages
        run: |
          git checkout gh-pages
          rm -rf README.md
          cp /tmp/README.md README.md
      - uses: stefanzweifel/git-auto-commit-action@v4

      


        