name: Update README
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  readme:
    name: Readme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Readme
        run: |
          ./generate-readme.sh
          cp README.md /tmp/README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Generate Readme gh-pages
        run: |
          git checkout gh-pages
          rm -rf README.md
          cp /tmp/README.md README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        # Push README.md to the langstream/documentation repository
      - name: Push to docs repo
        env:
            DOCS_REPO_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }} # Use the PAT stored in secrets
        run: |
          git clone https://github.com/langstream/documentation.git
          cd documentation
          rm -rf helm.md
          cp /tmp/README.md helm.md
          sed -i 's/# LangStream Helm Charts Repository/# LangStream Helm Chart Values/' helm.md
          git add helm.md
          git commit -m "Update helm documentation from charts repository"
          git push https://${DOCS_REPO_TOKEN}@github.com/langstream/documentation.git HEAD:main
      - uses: stefanzweifel/git-auto-commit-action@v4